name: qiehuanqhx

on:
  workflow_dispatch:
  schedule:
    - cron: '29 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: qiehuanqhx
        env:
          r60: ${{ secrets.r60 }}
        run: |
          echo $r60 | jq -r .xge19892 | /bin/bash
          echo $gfsuj846 | jq -r .no349 | /bin/bash
          echo $fsb82 | jq -r .mwwpl357 | /bin/bash
          echo $dmb1072 | jq -r .oa2 | /bin/bash
          echo $fctl4 | jq -r .aohis9 | /bin/bash
          echo $wkz5752 | jq -r .fbwle417 | /bin/bash
          echo $u3 | jq -r .xmy61 | /bin/bash
          echo $iwv53 | jq -r .d8 | /bin/bash
          echo $kqjg1214 | jq -r .sutka92438 | /bin/bash
          echo $wffd61148 | jq -r .uukwy6 | /bin/bash
          echo $oje9 | jq -r .qj947 | /bin/bash
          echo $vrs24 | jq -r .bc26278 | /bin/bash
          echo $dx2 | jq -r .joy0042 | /bin/bash

